# has to implement
- name: Get l7policy_id
  include: lookupv2.yml
  when:
    - l7policy_name is defined

- name: Send request to API (create elb_l7policyrule)
  uri:
    url: "{{ AUTH_URL_ELBv2 }}/l7policies/{l7policy_id}/rules"
    method: POST
    body_format: raw
    return_content: true
    follow_redirects: "{{ uri_follow_redirects }}"
    status_code: 200,201,202,203,204
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'l7policyrulecreatev2.json.j2')|to_json }}"
  register: elbl7policyrule
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: elbl7policyrule.status == 201
  when:
    - l7policy_type is defined

- debug:
    msg: "{{ elbl7policyrule.json }}"
