- name: Get listener_id
  include: lookupv2.yml
  when:
    - listener_name is defined

- name: Send request to API (create elb_listener)
  uri:
    url: "{{ AUTH_URL_ELBv2 }}/lbaas/listeners"
    method: POST
    body_format: raw
    return_content: true
    follow_redirects: "{{ uri_follow_redirects }}"
    status_code: 200,201,202,203,204
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'listenercreatev2.json.j2')|to_json }}"
  register: elblistner
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: elblistner.status == 201
  when:
    - elb_id is defined
    - listener_name is defined
    - not listener_id or listener_id is undefined

- debug:
    msg: "{{ elblistner }}"
