- name: Lookup elb_id
  delegate_to: "{{ delegateto }}"
  include: lookup.yml
  when:
    - elb_name is defined

- name: action {{ localaction }}
  delegate_to: "{{ delegateto }}"
  include: "{{ localaction }}.yml"
  when: localaction is defined
