- name: Get listener_id
  include: lookupv2.yml
  when:
    - elb_name is defined
    - listener_name is defined

- name: Send request to API (create elb_pool)
  uri:
    url: "{{ AUTH_URL_ELBv2 }}/lbaas/pools"
    method: POST
    body_format: raw
    return_content: true
    follow_redirects: "{{ uri_follow_redirects }}"
    status_code: 200,201,202,203,204
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'poolcreatev2.json.j2')|to_json }}"
  register: elbpool
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: elbpool.status == 201
  when:
    - pool_name is defined
    - elb_id is defined
    - listener_id is defined

- name: elbpool
  debug:
    msg: "{{ elbpool.json }}"
