- name: Lookup elb_id
  include: lookupv2.yml

- name: Send request to API (show ELB)
  uri:
    url: "{{ AUTH_URL_ELBv2 }}/lbaas/loadbalancers/{{ elb_id }}"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: elb
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: elb.status == 200
  changed_when: false
  when: elb_id is defined

- debug:
    msg: "{{ elb }}"
